### ISSUE TITLE
The mouse Event is not actually fired

### ISSUE THREAD

**Issue by ideepcoder** [Sentero-esp12/IsTrusted-event-Debugger-API#1]
I tried using your extension.

Following is output of real click
`MouseEvent {isTrusted: true, screenX: 0, screenY: 669, clientX: 0, clientY: 518, …}altKey: falsebubbles: truebutton: 0buttons: 0cancelBubble: falsecancelable: trueclientX: 0clientY: 518composed: truectrlKey: falsecurrentTarget: nulldefaultPrevented: falsedetail: 1eventPhase: 0fromElement: nullisTrusted: truelayerX: 0layerY: 664metaKey: falsemovementX: 0movementY: 0offsetX: 0offsetY: 397pageX: 0pageY: 664path: (13) [div.container, div#der-watch.tab-pane.fade.show.active, div.tab-content, div.col-xs-12.w-100, div.row, div.container-fluid, section#tabs.common-tabs, div.mid_body.live_mkt_watch, div.main, body, html..js.flexbox.flexboxlegacy.canvas.canvastext.webgl.no-touch.geolocation.postmessage.websqldatab…, document, Window]relatedTarget: nullreturnValue: truescreenX: 0screenY: 669shiftKey: falsesourceCapabilities: InputDeviceCapabilities {firesTouchEvents: false}srcElement: div.containertarget: div.containertimeStamp: 315706.01999992505toElement: div.containertype: "mouseup"view: Window {parent: Window, opener: null, top: Window, length: 1, frames: Window, …}which: 1x: 0y: 518__proto__: MouseEvent 53825.699999928474`

And this comes from your extension

`code.js:36 dispatching event, one moment
code.js:56 MouseEvent {isTrusted: true, screenX: 361, screenY: 155, clientX: 361, clientY: 155, …}altKey: falsebubbles: truebutton: 0buttons: 0cancelBubble: falsecancelable: trueclientX: 361clientY: 155composed: truectrlKey: falsecurrentTarget: nulldefaultPrevented: falsedetail: 0eventPhase: 0fromElement: nullisTrusted: truelayerX: 35layerY: 18metaKey: falsemovementX: 0movementY: 0offsetX: 36offsetY: 18pageX: 361pageY: 301path: (18) [span.activeTab, div#cree.custom_select.custom_close, div.selectbox.head_selectbox.posrel, div#some.tab-pane.fade.show.active, div.tab-content.py-3, div.container, div#my-watch.tab-pane.fade.show.active, div.tab-content, div.col-xs-12.w-100, div.row, div.container-fluid, section#tabs.common-tabs, div.main, body, html..js.flexbox.flexboxlegacy.canvas.canvastext.webgl.no-touch.geolocation.postmessage.websqldatab…, document, Window]relatedTarget: nullreturnValue: truescreenX: 361screenY: 155shiftKey: falsesourceCapabilities: InputDeviceCapabilities {firesTouchEvents: false}srcElement: span.activeTabtarget: span.activeTabtimeStamp: 317728.329999838toElement: span.activeTabtype: "mouseup"view: Window {parent: Window, opener: null, top: Window, length: 1, frames: Window, …}which: 1x: 361y: 155__proto__: MouseEvent 2.5100000202655792`

The install and permissions all look fine as the console shows the click getting fired each time. Mouse down / Mouse Up both but no action of the click itself. I tried a few webpages.

**Comment by Sentero-esp12** [comment]
Strange, the same is happening to me. 
This one worked partially: https://sketch.io/sketchpad/
But not consistently. 
I'm not yet sure what the reason could be. Maybe it miscalculates the position of the cursor.
