### ISSUE TITLE
How to implement keyBoard events 

### ISSUE THREAD

**Issue by whygithub7** [Sentero-esp12/IsTrusted-event-Debugger-API#2]
I need  keyBoard events  with isTrusted:true always after click on the extension icon ?
How i can do it ?
Nothing is clear in the official documentation. no experience in extension development.

**Comment by Sentero-esp12** [comment]
It's similar to the mouse event. You should read this: https://chromedevtools.github.io/devtools-protocol/tot/Input/#method-dispatchKeyEvent

**Comment by whygithub7** [comment]
I do not understand what all these properties mean, where to specify them and what they are eaten with

**Comment by whygithub7** [comment]
why your extension work only with first tab ? how fix it ?

**Comment by Sentero-esp12** [comment]
You need to attach `Debugger` to each tab you want to work with.

**Comment by whygithub7** [comment]
thanks. but i dont know how i can do it. i`ll attempt solve problem without your extension ,
